### ISSUE TITLE
ingest error

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis-chatta-demo#18]
when i run ./ingest.sh,it tooken an error:
Exception in thread "main" geotrellis.spark.io.package$LayerWriteError: Failed to write Layer(name = "SRTM", zoom = 13)
dose i make some uncorrect config?
did any body hited this error?
thanks!

**Comment by pomadchin** [comment]
@wsf1990 can you provide full stack trace?

**Comment by wsf1990** [comment]
ok,wait a moment.

**Comment by wsf1990** [comment]
OK,Like this,Thanks
Exception in thread "main" geotrellis.spark.io.package$LayerWriteError: Failed to write Layer(name = "SRTM", zoom = 13)
	at geotrellis.spark.io.accumulo.AccumuloLayerWriter._write(AccumuloLayerWriter.scala:52)
	at geotrellis.spark.io.accumulo.AccumuloLayerWriter._write(AccumuloLayerWriter.scala:17)
	at geotrellis.spark.io.LayerWriter$class.write(LayerWriter.scala:43)
	at geotrellis.spark.io.accumulo.AccumuloLayerWriter.write(AccumuloLayerWriter.scala:17)
	at geotrellis.spark.io.LayerWriter$$anon$1.write(LayerWriter.scala:55)
	at geotrellis.spark.io.LayerWriter$$anon$1.write(LayerWriter.scala:53)
	at geotrellis.spark.etl.OutputPlugin$class.apply(OutputPlugin.scala:21)
	at geotrellis.spark.etl.accumulo.SpatialAccumuloOutput.apply(SpatialAccumuloOutput.scala:11)
	at geotrellis.spark.etl.Etl.savePyramid$1(Etl.scala:173)
	at geotrellis.spark.etl.Etl.save(Etl.scala:187)
	at geotrellis.spark.etl.Etl$.ingest(Etl.scala:46)
	at geotrellis.chatta.ChattaIngest$delayedInit$body.apply(ChattaIngest.scala:17)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at geotrellis.chatta.ChattaIngest$.main(ChattaIngest.scala:15)
	at geotrellis.chatta.ChattaIngest.main(ChattaIngest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.accumulo.core.client.AccumuloException: Internal error processing waitForFateOperation
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:303)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:261)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doTableFateOperation(TableOperationsImpl.java:1427)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.importDirectory(TableOperationsImpl.java:1046)
	at geotrellis.spark.io.accumulo.HdfsWriteStrategy.write(AccumuloWriteStrategy.scala:67)
	at geotrellis.spark.io.accumulo.AccumuloRDDWriter$.write(AccumuloRDDWriter.scala:41)
	at geotrellis.spark.io.accumulo.AccumuloLayerWriter._write(AccumuloLayerWriter.scala:54)
	... 29 more
Caused by: org.apache.thrift.TApplicationException: Internal error processing waitForFateOperation
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.apache.accumulo.core.master.thrift.FateService$Client.recv_waitForFateOperation(FateService.java:174)
	at org.apache.accumulo.core.master.thrift.FateService$Client.waitForFateOperation(FateService.java:159)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.waitForFateOperation(TableOperationsImpl.java:233)
	at org.apache.accumulo.core.client.impl.TableOperationsImpl.doFateOperation(TableOperationsImpl.java:275)
	... 35 more

**Comment by pomadchin** [comment]
Is everything ok with your Accumulo?

**Comment by wsf1990** [comment]
yes,it create a table in Accumulo which I named in the ingest

**Comment by wsf1990** [comment]
I have resolved this, when I look the log of Accumulo ,it told me that the account of accumulo dont have the access write the hdfs,even though I dont know where use the account of accumulo ,but when I make the account of accumulo have the access to write hdfs,this problem had been resolved!
Many thanks!
