### ISSUE TITLE
ingest data fail

### ISSUE THREAD

**Issue by lovrth** [geotrellis/geotrellis-chatta-demo#52]
18/09/12 14:38:46 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
geotrellis.raster.io.geotiff.reader.MalformedGeoTiffException: incorrect byte order
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:272)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:97)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:82)
	at geotrellis.raster.io.geotiff.SinglebandGeoTiff$.apply(SinglebandGeoTiff.scala:101)
	at geotrellis.spark.io.RasterReader$$anon$1.readFully(RasterReader.scala:84)
	at geotrellis.spark.io.RasterReader$$anon$1.readFully(RasterReader.scala:82)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$$anonfun$apply$1$$anonfun$apply$2.apply(HadoopGeoTiffRDD.scala:111)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$$anonfun$apply$1$$anonfun$apply$2.apply(HadoopGeoTiffRDD.scala:110)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1011)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1009)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
18/09/12 14:38:46 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): geotrellis.raster.io.geotiff.reader.MalformedGeoTiffException: incorrect byte order
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:272)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:97)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:82)
	at geotrellis.raster.io.geotiff.SinglebandGeoTiff$.apply(SinglebandGeoTiff.scala:101)
	at geotrellis.spark.io.RasterReader$$anon$1.readFully(RasterReader.scala:84)
	at geotrellis.spark.io.RasterReader$$anon$1.readFully(RasterReader.scala:82)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$$anonfun$apply$1$$anonfun$apply$2.apply(HadoopGeoTiffRDD.scala:111)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$$anonfun$apply$1$$anonfun$apply$2.apply(HadoopGeoTiffRDD.scala:110)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1011)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1009)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by pomadchin** [comment]
Try to use tiff files from here: https://github.com/pomadchin/geotrellis-chatta-demo/tree/feature/cassandra-support/geotrellis/data/arg_wm

**Comment by pomadchin** [comment]
Also look through this thread: https://github.com/geotrellis/geotrellis-chatta-demo/issues/48
